//// Copyright 2025 Maor Avni
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define BOOTMAGIC_ROW 1
#define BOOTMAGIC_COLUMN 0
#define BOOTMAGIC_ROW_RIGHT 8
#define BOOTMAGIC_COLUMN_RIGHT 0
#define EE_HANDS

//#define MATRIX_ROW_PINS { GP4, GP5, GP6, GP7, GP8, GP9, GP10 }
//#define MATRIX_COL_PINS { GP29, GP28, GP27, GP26, GP22, GP21, GP20}
// #define MATRIX_ROW_PINS { GP29, GP28, GP27, GP26, GP11, GP21, GP20 }
// #define MATRIX_COL_PINS { GP2, GP3, GP4, GP5, GP6, GP7, GP10}

// SPI Configuration
// #define SPI_DRIVER SPID0
// #define SPI_SCK_PIN GP18
// #define SPI_MOSI_PIN GP19
// #define SPI_MISO_PIN GP16
// #define OLED_DC_PIN GP15
// #define OLED_CS_PIN GP17

// #define OLED_DISPLAY_128X64
// #define OLED_UPDATE_INTERVAL 50
// #define OLED_TIMEOUT 0
// #define OLED_IC SSD1306
